#!/bin/bash

clear
cd ~

ipaddr=""
default=$(wget -qO- ipv4.icanhazip.com);
read -p "IP address [$default]: " ipaddr
ipaddr=${ipaddr:-$default}

echo

echo -n "Update apt and upgrade installed packages... "
apt-get update -y > /dev/null 2>&1
apt-get upgrade -y > /dev/null 2>&1
echo "[ DONE ]"

echo -n "Install required and needed packages..."
apt-get install build-essential -y > /dev/null 2>&1
apt-get install screen zip grepcidr -y > /dev/null 2>&1
echo "[ DONE ]"

echo
sleep 3
cd

# openvpn
echo -n "Installing openvpn package... "
apt-get install openvpn -y > /dev/null 2>&1
apt-get install openssl -y > /dev/null 2>&1
apt-get install easy-rsa -y > /dev/null 2>&1
echo -e "[${green}DONE${noclr}]"

echo "Configure openvpn package... "
openssl dhparam -out /etc/openvpn/dh2048.pem 2048

cp -r /usr/share/easy-rsa/ /etc/openvpn

sed -i 's|export KEY_COUNTRY="US"|export KEY_COUNTRY="MY"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_PROVINCE="CA"|export KEY_PROVINCE="Sabah"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_CITY="SanFrancisco"|export KEY_CITY="Tawau"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_ORG="Fort-Funston"|export KEY_ORG="VPS-Knowledge"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_EMAIL="me@myhost.mydomain"|export KEY_EMAIL="vps.doctype@gmail.com"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_OU="MyOrganizationalUnit"|export KEY_OU="Doctype"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_NAME="EasyRSA"|export KEY_NAME="KnowledgeRSA"|' /etc/openvpn/easy-rsa/vars

cd /etc/openvpn/easy-rsa
ln -s openssl-1.0.0.cnf openssl.cnf
source ./vars
./clean-all
./build-ca
./build-key-server --batch server
./build-key --batch client

cd

cp /etc/openvpn/easy-rsa/keys/ca.crt /etc/openvpn
cp /etc/openvpn/easy-rsa/keys/ca.key /etc/openvpn
cp /etc/openvpn/easy-rsa/keys/dh2048.pem /etc/openvpn
cp /etc/openvpn/easy-rsa/keys/server.crt /etc/openvpn
cp /etc/openvpn/easy-rsa/keys/server.key /etc/openvpn
cp /etc/openvpn/easy-rsa/keys/client.crt /etc/openvpn
cp /etc/openvpn/easy-rsa/keys/client.key /etc/openvpn


cat > /etc/openvpn/server.conf <<-EOF
port 1194
proto tcp
dev tun

ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
dh /etc/openvpn/dh2048.pem

server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
user nobody
group nogroup
persist-key
persist-tun
auth SHA256
cipher AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
status vpn-status.log
log /var/log/openvpn.log
comp-lzo
verb 3
mute 20
EOF

systemctl start openvpn@server

cat > /etc/openvpn/client.ovpn <<-EOF
client
dev tun
proto tcp-client
remote $ipaddr 1194
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
auth SHA256
auth-nocache
ns-cert-type server
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256

;http-proxy-retry
;http-proxy [squid] [port]
;http-proxy-option CUSTOM-HEADER Host [host]
;http-proxy-option CUSTOM-HEADER X-Online-Host [host]

mute-replay-warnings
auth-user-pass
comp-lzo
verb 3
mute 20
EOF

echo '' >> /etc/openvpn/client.ovpn
echo '<ca>' >> /etc/openvpn/client.ovpn
cat /etc/openvpn/easy-rsa/keys/ca.crt >> /etc/openvpn/client.ovpn
echo '</ca>' >> /etc/openvpn/client.ovpn
echo "DONE"
/etc/init.d/openvpn restart

echo
sleep 3

echo "You need to reboot for change to take action."
